// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiNnUoLwhVqUuCIprZ7A4ay9Jl04Gt9nY',
    appId: '1:771204595815:web:c5350fbdf956a7a7d154c2',
    messagingSenderId: '771204595815',
    projectId: 'emely-93065',
    authDomain: 'emely-93065.firebaseapp.com',
    storageBucket: 'emely-93065.firebasestorage.app',
    measurementId: 'G-94YB531D56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_9sp2Ej1xGu9O2Hy1aq89qD95LjcC-3g',
    appId: '1:771204595815:android:986723ffdd333d41d154c2',
    messagingSenderId: '771204595815',
    projectId: 'emely-93065',
    storageBucket: 'emely-93065.firebasestorage.app',
  );
}
